### ISSUE TITLE
Questions that imply an image should be displayed do not display an image

### ISSUE THREAD

**Issue by jacquimai** [dannyeldridge/jeopardy#2]
Would there be a way to exclude questions that originally had an image attached?

![Screenshot 2024-04-30 at 10 17 57 AM](https://github.com/dannyeldridge/jeopardy/assets/91088795/d55fbd33-53ee-4ba7-8305-a93bb6e92390)

**Comment by dannyeldridge** [comment]
I'll have to change this on the app that serves the questions, but yes, will do!

**Comment by dannyeldridge** [comment]
@jacquimai Should be fixed now
